version: "1"
services:
  front:
    build: 
      context: .
      dockerfile: Dockerfile
    environment:
      NODE_ENV: development
    env_file:
      - ./.env
    ports:
      - "3003:3003"
    volumes:
      - .:/app
      - ./node_modules:/home/nodejs/node_modules
      - .env:/app/.env
      # auto reload
      - .:/app/src
      # prevent node_modules from being copied to the container
      - /app/node_modules